# syntax=docker/dockerfile:1

ARG NODE_VERSION=24.1.0
ARG PNPM_VERSION=10.18.1

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV=development

# Install pnpm.
RUN --mount=type=cache,target=/root/.npm \
    npm install -g pnpm@${PNPM_VERSION}

WORKDIR /usr/src/app

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.local/share/pnpm/store to speed up subsequent builds.
# Leverage a bind mounts to package.json and pnpm-lock.yaml to avoid having to copy them into
# into this layer.
RUN --mount=type=bind,source=fimidara-server-node/package.json,target=fimidara-server-node/package.json \
    --mount=type=bind,source=pnpm-lock.yaml,target=pnpm-lock.yaml \
    --mount=type=bind,source=pnpm-workspace.yaml,target=pnpm-workspace.yaml \
    --mount=type=cache,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile --filter fimidara-server-node

# Copy the rest of the source files into the image.
COPY . .

# Change to the specific package directory
WORKDIR /usr/src/app/fimidara-server-node

# Run the application.
CMD ["pnpm", "dev"]
